{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Business Partners",
    "description" : "Enables you to create and manage business partner data, including customer data, contact data, and customer-contact relationships.",
    "version" : "3"
  },
  "x-sap-extensible": {
    "supported": "automatic",
    "description": "The API can be extended by using custom references. For more information, refer to [Custom References](https://help.sap.com/docs/CLOUD_TO_CASH_OD/e4aa21cd43494cc1a8a90ea0f3dab8bb/1a8601ce8db44b2b8e29012d385892ca.html#custom-references) on the SAP Help Portal."
  },
  "servers" : [ {
    "url" : "https://sandbox.api.sap.com/subscriptionbilling/api/business-partner/v3"
  }, {
    "url" : "https://{region}.revenue.cloud.sap/api/business-partner/v3",
    "description" : "SAP Subscription Billing API Endpoint",
    "variables" : {
      "region" : {
        "description" : "SAP Subscription Billing Region",
        "enum" : [ "eu10", "us10" ],
        "default" : "eu10"
      }
    }
  } ],
  "security" : [ {
    "oauth2" : [ "{identityzone}.business-partner-customer_manage", "{identityzone}.business-partner-customer_view", "{identityzone}.business-partner-customer_delete", "{identityzone}.business-partner-contact_manage", "{identityzone}.business-partner-contact_view", "{identityzone}.business-partner-mdi-replication-report_view" ]
  } ],
  "tags" : [ {
    "name" : "Customer Management",
    "description" : "Manage customer data."
  }, {
    "name" : "Contact Management",
    "description" : "Manage contact data."
  }, {
    "name" : "Relationship Management",
    "description" : "Manage customer-contact relationship data."
  }, {
    "name" : "Replication Monitoring",
    "description" : "Monitor SAP Master Data Integration Replication."
  } ],
  "paths" : {
    "/customers" : {
      "get" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Retrieves customers.",
        "description" : "Retrieves a collection of customers that match the search criteria.<br><br>This operation requires the scope `business-partner-customer_view`.",
        "operationId" : "GET_customers",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_view" ]
        } ]
      },
      "post" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Creates a customer.",
        "description" : "Before you use this operation, check the [API Guide](https://help.sap.com/viewer/987aec876092428f88162e438acf80d6/latest/en-US/7373ddb2b26d4b25b4b7768eb8d24f72.html) for important information.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "POST_customers",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      }
    },
    "/customers/{customerNumber}" : {
      "get" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Retrieves a customer.",
        "description" : "Retrieves a single customer with a specific identifier.<br><br>This operation requires the scope `business-partner-customer_view`.",
        "operationId" : "GET_customers-customerNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Updates a customer.",
        "description" : "Updates a single customer with a specific identifier.<br>Before you use this operation, check the [API Guide](https://help.sap.com/viewer/987aec876092428f88162e438acf80d6/latest/en-US/1869a4d94786454e89935d860114c2a6.html) for important information.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "PUT_customers-customerNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Delete a customer.",
        "description" : "Deletes a single customer with a specific identifier. The customer cannot be deleted when there are existing documents.<br><br>This operation requires the scope `business-partner-customer_delete`.",
        "operationId" : "DELETE_customers-customerNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_delete" ]
        } ]
      }
    },
    "/customers/{customerNumber}/externalObjectReferences" : {
      "get" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Retrieves external object references for a customer.",
        "description" : "Retrieves the external object references for a single customer with a specific identifier.<br><br>This operation requires the scope `business-partner-customer_view`.",
        "operationId" : "GET_customers-customerNumber-externalObjectReferences",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Customer Management" ],
        "summary" : "Updates external object references for a customer.",
        "description" : "Updates the external object references for a single customer with a specific identifier.<br>Before you use this operation, check the [API Guide](https://help.sap.com/viewer/987aec876092428f88162e438acf80d6/latest/en-US/15c565f688684c1f8219e8369ff3813f.html) for important information.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "PUT_customers-customerNumber-externalObjectReferences",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      }
    },
    "/contacts" : {
      "get" : {
        "tags" : [ "Contact Management" ],
        "summary" : "Retrieves contacts.",
        "description" : "Retrieves a collection of contacts that match the search criteria.<br><br>This operation requires the scope `business-partner-contact_view`.",
        "operationId" : "GET_contacts",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-contact_view" ]
        } ]
      },
      "post" : {
        "tags" : [ "Contact Management" ],
        "summary" : "Creates a contact.",
        "description" : "Creates a new contact.<br><br>This operation requires the scope `business-partner-contact_manage`.",
        "operationId" : "POST_contacts",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-contact_manage" ]
        } ]
      }
    },
    "/contacts/{contactNumber}" : {
      "get" : {
        "tags" : [ "Contact Management" ],
        "summary" : "Retrieves a contact.",
        "description" : "Retrieves a single contact with a specific identifier.<br><br>This operation requires the scope `business-partner-contact_view`.",
        "operationId" : "GET_contacts-contactNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-contact_view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Contact Management" ],
        "summary" : "Updates a contact.",
        "description" : "Updates a single contact with a specific identifier.<br><br>This operation requires the scope `business-partner-contact_manage`.",
        "operationId" : "PUT_contacts-contactNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-contact_manage" ]
        } ]
      }
    },
    "/contacts/{contactNumber}/externalObjectReferences" : {
      "get" : {
        "tags" : [ "Contact Management" ],
        "summary" : "Retrieve external object references for a contact.",
        "description" : "Retrieves the external object references for a single contact with a specific identifier.<br><br>This operation requires the scope `business-partner-contact_view`.",
        "operationId" : "GET_contacts-contactNumber-externalObjectReferences",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-contact_view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Contact Management" ],
        "summary" : "Updates external object references for a contact.",
        "description" : "Updates the external object references for a single contact with a specific identifier.<br>Before you use this operation, check the [API Guide](https://help.sap.com/viewer/987aec876092428f88162e438acf80d6/latest/en-US/ac792f993e314ea18dd75b4a99f61a48.html) for important information.<br><br>This operation requires the scope `business-partner-contact_manage`.",
        "operationId" : "PUT_contacts-contactNumber-externalObjectReferences",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-contact_manage" ]
        } ]
      }
    },
    "/relationships/customer-contacts" : {
      "get" : {
        "tags" : [ "Relationship Management" ],
        "summary" : "Retrieve relationships between customers and contacts.",
        "description" : "Retrieves a collection of customer-contact relationships.<br><br>This operation requires the scope `business-partner-customer_view`.",
        "operationId" : "GET_relationships-customer-contacts",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_view" ]
        } ]
      }
    },
    "/relationships/customer-contacts/{customerNumber}" : {
      "get" : {
        "tags" : [ "Relationship Management" ],
        "summary" : "Retrieve customer-contact relationships for a customer.",
        "description" : "Retrieves a collection of customer-contact relationships for the given customer.<br><br>This operation requires the scope `business-partner-customer_view`.",
        "operationId" : "GET_relationships-customer-contacts-customernumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_view" ]
        } ]
      }
    },
    "/relationships/customer-contacts/{customerNumber}/{contactNumber}" : {
      "put" : {
        "tags" : [ "Relationship Management" ],
        "summary" : "Creates or updates the customer-contact relationship.",
        "description" : "Creates or updates the relationship between a customer and a contact with specified IDs.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "PUT_relationships-customer-contacts-customerNumber-contactNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Relationship Management" ],
        "summary" : "Deletes the customer-contact relationship.",
        "description" : "Deletes the relationship between a customer and a contact with specified IDs.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "DELETE_relationships-customer-contacts-customerNumber-contactNumber",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      }
    },
    "/relationships/customer-contacts/{customerNumber}/{contactNumber}/state" : {
      "post" : {
        "tags" : [ "Relationship Management" ],
        "summary" : "Assigns the default customer-contact relationship.",
        "description" : "Assigns the default relationship between a customer and a contact.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "POST_relationships-customer-contacts-customerNumber-contactNumber-state",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      }
    },
    "/relationships/customer-contacts/replicationConfirmation" : {
      "post" : {
        "tags" : [ "Relationship Management" ],
        "summary" : "Confirms replication of the customer-contact relationship.",
        "description" : "Confirms that the customer-contact relationship was replicated.<br><br>This operation requires the scope `business-partner-customer_manage`.",
        "operationId" : "POST_relationships-customer-contacts-replicationConfirmation",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-customer_manage" ]
        } ]
      }
    },
    "/mdi/replication-reports" : {
      "get" : {
        "tags" : [ "Replication Monitoring" ],
        "summary" : "Retrieves SAP Master Data Integration business partner replication reports.",
        "description" : "Retrieves a collection of SAP Master Data Integration replication reports that match the search criteria.<br><br>This operation requires the scope `business-partner-mdi-replication-report_view`.",
        "operationId" : "GET_mdi_replication_reports",
        "security" : [ {
          "oauth2" : [ "{identityzone}.business-partner-mdi-replication-report_view" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "description" : "To use this API, log on to the SAP BTP (Business Technology Platform) cockpit to get a service key with OAuth client credentials. Then use the service key to generate an access/bearer token. <br>For more information, see the API Guide.",
        "flows" : {
          "clientCredentials" : {
            "tokenUrl" : "https://{identityzone}.authentication.{region}.hana.ondemand.com/oauth/token",
            "scopes" : {
              "{identityzone}.business-partner-customer_manage" : "Create or update customer data.",
              "{identityzone}.business-partner-customer_view" : "View customer data.",
              "{identityzone}.business-partner-customer_delete" : "Delete customer data.",
              "{identityzone}.business-partner-contact_manage" : "Create or update contact data.",
              "{identityzone}.business-partner-contact_view" : "View contact data.",
              "{identityzone}.business-partner-mdi-replication-report_view" : "View SAP Master Data Integration Replication reports."
            }
          }
        }
      }
    }
  },
  "x-sap-shortText" : "Manage business partners, including customers and contacts."
}